<?php

function fpa_menu() {
  $items = array();
  
  $items['fpa_modal/%ctools_js/permissions'] = array(
      'title' => 'Permissions',
      'page callback' => '_fpa_ctools',
      'page arguments' => array(1, 3),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function fpa_form_alter(&$form, &$form_state, $form_id) {
  
  switch ($form_id) {
    case 'content_field_edit_form':
      if ((module_exists('content_permissions') || module_exists('field_permissions'))) {
        $perm = $form['#field']['field_name'];
        $pos = &$form['field'];
      }
      break;
    case 'node_type_form':
      $perm = $form['#node_type']->type .' content';
      $pos = &$form;
      break;
  }
  
  if (isset($perm) && user_access('administer permissions')) {
    
    $fpa_path = drupal_get_path('module', 'fpa');
    
    $pos['fpa_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t('Permissions'),
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,
      '#description' => t('Clicking on this link will launch a modal/tab/window displaying the appropriate permissions.'),
    );
    
    $pos['fpa_fieldset']['fpa'] = array(
      '#type' => 'markup',
    );
    
    if (module_exists('ctools')) {
      ctools_add_js('fpa', 'fpa');
      ctools_add_css('fpa', 'fpa');
      ctools_include('ajax');
      ctools_include('modal');
      ctools_modal_add_js();
      
      $pos['fpa_fieldset']['fpa']['#value'] = ctools_modal_text_button(t('Manage Permissions'), 'fpa_modal/nojs/permissions/'.urlencode($perm), t('Login via modal'),  'ctools-modal-ctools-sample-style');
    }
    elseif (module_exists('modalframe')) {
      modalframe_parent_js();
      drupal_add_js($fpa_path .'/js/fpa.js', 'module');
      $pos['fpa_fieldset']['fpa']['#value'] = l('Manage Permissions', 'admin/user/permissions', array('query' => array('fpa_perm' => $perm, 'fpa_method' => 'modalframe'), 'attributes' => array('class' => 'fpa_modalframe')));
    }
    else {
      $pos['fpa_fieldset']['fpa']['#value'] = l('Manage Permissions', 'admin/user/permissions', array('query' => array('fpa_perm' => $perm), 'attributes' => array('target' => '_blank')));
    }
    
  }
}

function fpa_form_user_admin_perm_alter(&$form, &$form_state) {
  if (isset($_GET['fpa_perm'])) {
    if (isset($_GET['fpa_method']) && $_GET['fpa_method'] == 'modalframe') {
      modalframe_child_js();
      $form['#submit'][] = '_fpa_modalframe_submit';
    }
    $fpa_path = drupal_get_path('module', 'fpa');
    drupal_add_css($fpa_path .'/css/fpa.css', 'module');
    drupal_add_js($fpa_path .'/js/fpa.js', 'module');
    drupal_add_js(array('fpa_perm' => $_GET['fpa_perm']), 'setting');
  }
}

function _fpa_modalframe_submit() {
  modalframe_close_dialog();
}

function _fpa_ctools($js = NULL, $perm) {
  // Need to include the file that contains the permissions form.
  module_load_include('inc', 'user', 'user.admin');
  // Fall back if $js is not set.
  if (!$js) {
    return drupal_get_form('user_admin_perm');
  }

  ctools_include('modal');
  ctools_include('ajax');
  $form_state = array(
    'title' => t('Permissions'),
    'ajax' => TRUE,
  );
  $output = ctools_modal_form_wrapper('user_admin_perm', $form_state);
  
  if (empty($output)) {
    $output = array(ctools_ajax_command_reload());
  }
  else {
    drupal_add_js(array('fpa_perm' => $perm), 'setting');
  }
  
  ctools_ajax_render($output);
}